<?php

return [
    'site_title' => 'Innoversion Technolab',

    'defaults' => [
        'description' => 'Innoversion Technolab provides software development, web solutions, mobile apps, and digital transformation services.',
        'keywords' => 'Innoversion Technolab, software development, web development, mobile app development, digital transformation, IT services',
    ],

    'routes' => [
        'frontend.home' => [
            'title' => 'Top Software Development Company in Gujarat| Web, Mobile App & SaaS Solutions',
            'description' => 'Innoversion Technolab is a top software development company in Rajkot offering web development, mobile apps, SaaS solutions, API integration, and SEO services.',
            'keywords' => 'custom software development company Gujarat, web application development services Gujarat, mobile app development company Gujarat, SaaS development company Gujarat, software development agency India Gujarat, IT solutions company Gujarat, full stack development company Gujarat, API integration services Gujarat, workflow automation solutions Gujarat, UI UX design services Gujarat, digital marketing and SEO services Gujarat, Shopify development company Gujarat, WordPress development services Gujarat, eCommerce development company Gujarat, React.js development Gujarat, Node.js development Gujarat, Laravel development Gujarat, Python development Gujarat, Flutter app development Gujarat, DevOps services Gujarat, AWS cloud services Gujarat, software development company in Rajkot Gujarat, web development company in Rajkot Gujarat, mobile app development in Rajkot Gujarat, SEO services in Rajkot Gujarat, IT company in Gujarat',
        ],
        'home' => [
            'title' => 'Top Software Development Company in Gujarat| Web, Mobile App & SaaS Solutions',
            'description' => 'Innoversion Technolab is a top software development company in Rajkot offering web development, mobile apps, SaaS solutions, API integration, and SEO services.',
            'keywords' => 'custom software development company Gujarat, web application development services Gujarat, mobile app development company Gujarat, SaaS development company Gujarat, software development agency India Gujarat, IT solutions company Gujarat, full stack development company Gujarat, API integration services Gujarat, workflow automation solutions Gujarat, UI UX design services Gujarat, digital marketing and SEO services Gujarat, Shopify development company Gujarat, WordPress development services Gujarat, eCommerce development company Gujarat, React.js development Gujarat, Node.js development Gujarat, Laravel development Gujarat, Python development Gujarat, Flutter app development Gujarat, DevOps services Gujarat, AWS cloud services Gujarat, software development company in Rajkot Gujarat, web development company in Rajkot Gujarat, mobile app development in Rajkot Gujarat, SEO services in Rajkot Gujarat, IT company in Gujarat',
        ],
    ],

    'services' => [
        'custom-software-development' => [
            'title' => 'Custom Software Development Company in Rajkot, Gujarat | Scalable IT Solutions India',
            'description' => 'Custom software development company in Rajkot, Gujarat, India delivering scalable web, mobile, SaaS solutions, API integration, and business automation services.',
            'keywords' => 'custom software development Gujarat, software development services Gujarat, custom software development companies Gujarat, custom software development company Gujarat, top custom software development companies Gujarat, affordable custom software development company in India Gujarat, custom software development services Gujarat, custom software development company for startups Gujarat, affordable software development company in Rajkot Gujarat, hire custom software developers India Gujarat, best software company in Rajkot Gujarat, custom ERP software development services Gujarat, benefits of custom software for business Gujarat, CRM software development company for small business Gujarat, custom software development solutions Gujarat, custom SaaS development services for startups Gujarat, custom software services Gujarat, web based custom software development solutions Gujarat, cost effective custom software development services Gujarat, ERP development services Gujarat, custom business automation software development Gujarat, on demand software development company India Gujarat',
        ],
        'web-application-development' => [
            'title' => 'Top Web Application Development in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers top web application development in Rajkot, Gujarat, India with scalable, secure web apps, SaaS solutions, API integration services.',
            'keywords' => 'web application development company Gujarat, affordable web application development company in India Gujarat, best web application development company Gujarat, custom web app development company for startups Gujarat, top web application development company Gujarat, hire web application developers India Gujarat, affordable web application development services Gujarat, scalable web application development services Gujarat, affordable custom web application development services Gujarat, secure web application development company Gujarat, professional web application development company in India Gujarat, web based software development solutions for business Gujarat, B2B web application development agency Gujarat, build custom web application for business Gujarat, affordable web app development services for small business Gujarat, cost effective web app development services Gujarat, scalable web app development for startups Gujarat, cloud based web application development company Gujarat, web app development for business automation solutions Gujarat, on demand web application development services Gujarat, custom CRM web app development for small business Gujarat',
        ],
        'mobile-app-development' => [
            'title' => 'Best Mobile Application Development in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab delivers best mobile app development in Rajkot, Gujarat, India with scalable Android, iOS apps, UI/UX design, API integration, and secure solutions.',
            'keywords' => 'mobile app development company Gujarat, Flutter app development company India Gujarat, mobile app development services Gujarat, React Native app development services Gujarat, app development company India Gujarat, Android app development using Kotlin Gujarat, custom mobile app development Gujarat, iOS app development using Swift Gujarat, Android app development company Gujarat, cross platform mobile app development company Gujarat, iOS app development company Gujarat, hybrid mobile app development services Gujarat, cross platform app development Gujarat, API integration in mobile apps Gujarat, mobile application developers India Gujarat, affordable mobile app development company in India Gujarat, custom mobile app development company for startups Gujarat, hire mobile app developers India Gujarat, cost effective mobile app development services Gujarat, scalable mobile app development solutions Gujarat, on demand mobile app development company Gujarat, mobile app development services for small business Gujarat, build custom mobile app for business Gujarat, startup mobile app development company India Gujarat, enterprise mobile app development services Gujarat',
        ],
        'saas-development' => [
            'title' => 'Best SaaS Development Firm in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers best SaaS development in Rajkot, Gujarat, India with scalable cloud apps, secure architecture, API integration, and startup-friendly solutions.',
            'keywords' => 'affordable SaaS development company in India Gujarat, subscription based software development Gujarat, SaaS product development company for startups Gujarat, build SaaS application with subscription model for business Gujarat, hire SaaS developers India Gujarat, end to end SaaS product development services in India Gujarat, custom SaaS application development services Gujarat, affordable SaaS development company in Rajkot Gujarat, scalable SaaS platform development company Gujarat, SaaS product development services in Rajkot India Gujarat, cost effective SaaS development services Gujarat, best SaaS development company for startups in Gujarat, build SaaS product for business Gujarat, hire SaaS developers in Rajkot India Gujarat, multi tenant SaaS application development Gujarat, SaaS development agency near me for startups Gujarat, SaaS MVP development company Gujarat, custom SaaS application development company in Gujarat, cloud SaaS development solutions for startups Gujarat, SaaS development company in Rajkot Gujarat, SaaS developers in Gujarat India Gujarat, best SaaS development company in Rajkot Gujarat, SaaS application development services in Gujarat, SaaS development company near me Gujarat, affordable SaaS developers in Rajkot Gujarat',
        ],
        'api-integration-services' => [
            'title' => 'API Integration Services in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers API integration services in Rajkot, Gujarat, India with secure, scalable integrations, payment gateways, CRM, and third-party APIs.',
            'keywords' => 'affordable API integration services in India Gujarat, custom API integration services for startups Gujarat, third party API integration company for business Gujarat, secure API integration services for web applications Gujarat, API integration services for mobile apps Gujarat, API integration company for SaaS platforms Gujarat, scalable API integration services for enterprises Gujarat, API integration solutions for small business Gujarat, cost effective API integration company India Gujarat, end to end API integration services Gujarat, API integration company in Rajkot Gujarat, API integration services in Gujarat India Gujarat, best API integration company in Rajkot Gujarat, API developers in Gujarat India Gujarat, API integration company near me Gujarat, affordable API integration services in Rajkot Gujarat',
        ],
        'workflow-automation' => [
            'title' => 'Top Workflow Automation Services in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers workflow automation services in Rajkot, Gujarat, India to streamline operations, reduce manual tasks, and boost efficiency with smart solutions.',
            'keywords' => 'workflow automation services Gujarat, CRM workflow automation services Gujarat, business workflow automation Gujarat, HR workflow automation solutions Gujarat, workflow automation solutions Gujarat, sales process automation services Gujarat, process automation services Gujarat, invoice and billing workflow automation Gujarat, workflow automation company Gujarat, email automation workflow services Gujarat, business process automation services Gujarat, lead management workflow automation Gujarat, custom workflow automation Gujarat, document workflow automation solutions Gujarat, affordable workflow automation services for small business Gujarat, workflow automation services in Rajkot Gujarat, custom workflow automation solutions for startups Gujarat, business automation company in Gujarat India Gujarat, business process automation company in India Gujarat, workflow automation company in Rajkot Gujarat, automate business workflows using software solutions Gujarat, process automation services near me Gujarat, workflow automation services for web applications Gujarat, affordable workflow automation company in Gujarat, scalable workflow automation solutions for enterprises Gujarat, cloud based workflow automation services Gujarat, cost effective business workflow automation services Gujarat, workflow automation company for startups India Gujarat, end to end workflow automation solutions Gujarat',
        ],
        'ui-ux-design' => [
            'title' => 'UI/UX Design Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab is a UI/UX design company in Rajkot, Gujarat, India creating user-friendly, modern designs for web and mobile apps to improve engagement.',
            'keywords' => 'affordable UI UX design services for startups in India Gujarat, AI UI UX design services Gujarat, custom UI UX design company for web applications Gujarat, modern UI UX design trends Gujarat, UI UX design agency for mobile apps India Gujarat, UX optimization services Gujarat, hire UI UX designers India for startup projects Gujarat, conversion focused UI UX design Gujarat, UI UX design services for SaaS platforms Gujarat, user centered design services Gujarat, cost effective UI UX design company India Gujarat, UX audit services Gujarat, UI UX redesign services for existing websites Gujarat, design system development services Gujarat, modern UI UX design services for business websites Gujarat, UX strategy consulting services Gujarat, scalable UI UX design solutions for startups Gujarat, UI UX design company for small businesses Gujarat, UI UX design company in Rajkot Gujarat, UI UX designers in Gujarat India Gujarat, best UI UX design agency in Rajkot Gujarat, UI UX design services near me Gujarat, affordable UI UX company in Gujarat, professional UI UX design services for business Gujarat, custom UI UX design company India Gujarat',
        ],
        'digital-marketing-seo' => [
            'title' => 'Digital Marketing & SEO Services in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab is a digital marketing and SEO services provider in Rajkot, Gujarat, India helping businesses grow with ranking, traffic, and leads.',
            'keywords' => 'affordable digital marketing services for small business in India Gujarat, social media marketing services for small business in India Gujarat, SEO services for startups in India Gujarat, Google Ads management services for lead generation in India Gujarat, best digital marketing company in Rajkot Gujarat, PPC advertising services for startups in India Gujarat, local SEO services for small businesses Gujarat, content marketing services for business growth in India Gujarat, ecommerce SEO services company India Gujarat, email marketing services for customer engagement in India Gujarat, hire SEO expert in India for business growth Gujarat, online marketing services for local businesses in India Gujarat, digital marketing agency for lead generation Gujarat, digital marketing services in Rajkot Gujarat for small business Gujarat, SEO services for website ranking improvement Gujarat, SEO services in Rajkot Gujarat for website ranking Gujarat, cost effective digital marketing services India Gujarat, local SEO services in Rajkot for business growth Gujarat, digital marketing services for startups Gujarat, affordable digital marketing services in Gujarat India Gujarat, social media marketing services Gujarat, best SEO services company in Rajkot Gujarat India Gujarat, Google Ads management services Gujarat, digital marketing services near me for local business Gujarat, PPC advertising services Gujarat, SEO services near me for small business growth Gujarat, content marketing services Gujarat, digital marketing services in India with affordable pricing Gujarat, email marketing services Gujarat, SEO services in India with guaranteed results Gujarat, on page SEO services Gujarat, digital marketing services in Gujarat for startups Gujarat, off page SEO services Gujarat, technical SEO services Gujarat, local SEO services Gujarat, ecommerce SEO services Gujarat',
        ],
    ],

    'technologies' => [
        'react' => [
            'title' => 'React.js Development Services in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers React.js development services in Rajkot, Gujarat, India building fast, scalable web apps with modern UI, API integration, and support.',
            'keywords' => 'affordable React.js development services for startups in India Gujarat, best React.js development company for web applications in India Gujarat, custom React.js web application development services for business Gujarat, professional React.js development services for scalable web apps Gujarat, cost effective React.js development company in India Gujarat, React.js development services in Rajkot Gujarat India Gujarat, best React.js developers in Rajkot for web development Gujarat, affordable React.js development company in Gujarat India Gujarat, hire React.js developers in Rajkot Gujarat Gujarat, React.js development services near me for business Gujarat, React.js development company in Rajkot Gujarat India Gujarat, React.js development company for single page applications Gujarat, React.js UI development services for responsive websites Gujarat, React.js development services for custom dashboards Gujarat, React.js integration services with backend API development Gujarat, React.js migration services from Angular to React Gujarat, React.js development services for startup MVP projects Gujarat',
        ],
        'vue' => [
            'title' => 'Vue.js Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab is a Vue.js development company in Rajkot, Gujarat, India building fast, scalable web apps with modern UI, API integration, and support.',
            'keywords' => 'affordable Vue.js development services for startups in India Gujarat, best Vue.js development company for web applications in India Gujarat, custom Vue.js web application development services for business Gujarat, hire Vue.js developers in India for frontend development Gujarat, Vue.js frontend development services for modern websites Gujarat, Vue.js development company for SaaS applications in India Gujarat, Vue.js single page application development services Gujarat, Vue.js ecommerce website development services in India Gujarat, Vue.js dashboard development services for business applications Gujarat, Vue.js integration services with REST API and backend Gujarat, outsource Vue.js development services to India company Gujarat, Vue.js development services with support and maintenance Gujarat, scalable Vue.js development services for startups Gujarat, Vue.js responsive UI development services for mobile and web Gujarat, Vue.js development company in Rajkot Gujarat India Gujarat',
        ],
        'angular' => [
            'title' => 'Angular.js Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab is an Angular.js development company in Rajkot, Gujarat, India delivering scalable web apps with modern UI, API integration, and support.',
            'keywords' => 'affordable Angular.js development services for startups in India Gujarat, best Angular.js development company for web applications in India Gujarat, custom Angular.js web application development services for business Gujarat, hire Angular.js developers in India for frontend development Gujarat, Angular.js frontend development services for modern websites Gujarat, Angular.js development company for SaaS applications in India Gujarat, Angular.js single page application development services Gujarat, Angular.js ecommerce website development services in India Gujarat, Angular.js dashboard development services for business applications Gujarat, Angular.js integration services with REST API and backend Gujarat, outsource Angular.js development services to India company Gujarat, Angular.js development services with support and maintenance Gujarat, scalable Angular.js development services for startups Gujarat, Angular.js responsive UI development services for mobile and web Gujarat, Angular.js development company in Rajkot Gujarat India Gujarat',
        ],
        'node-js' => [
            'title' => 'Node.js Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab delivers Node.js development in Rajkot, Gujarat, India—crafting high-performance APIs, real-time apps, and scalable backend systems with cloud support.',
            'keywords' => 'affordable Node.js development services for startups in India Gujarat, best Node.js development company for backend development in India Gujarat, custom Node.js web application development services for business Gujarat, hire Node.js developers in India for backend development Gujarat, Node.js backend development services for scalable web applications Gujarat, Node.js development company for SaaS applications in India Gujarat, Node.js API development and integration services Gujarat, Node.js ecommerce website development services in India Gujarat, Node.js microservices development services for enterprise applications Gujarat, Node.js real time application development services Gujarat, outsource Node.js development services to India company Gujarat, Node.js development services with support and maintenance Gujarat, scalable Node.js development services for startups Gujarat, Node.js cloud based application development services Gujarat, Node.js development company in Rajkot Gujarat India Gujarat',
        ],
        'laravel' => [
            'title' => 'Laravel Development Firm in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab is a Laravel development company in Rajkot, Gujarat, India building secure, scalable web apps, APIs, and custom business solutions with expert support.',
            'keywords' => 'affordable Laravel development services for startups in India Gujarat, best Laravel development company for web applications in India Gujarat, custom Laravel web application development services for business Gujarat, hire Laravel developers in India for backend development Gujarat, Laravel development services for scalable web applications Gujarat, Laravel ecommerce website development services in India Gujarat, Laravel API development and integration services Gujarat, Laravel development company for SaaS applications in India Gujarat, Laravel CRM and ERP development services for business Gujarat, outsource Laravel development services to India company Gujarat, Laravel development services with support and maintenance Gujarat, scalable Laravel development services for startups Gujarat, Laravel migration and upgrade services for web applications Gujarat, Laravel backend development services for enterprise solutions Gujarat, Laravel development company in Rajkot Gujarat India Gujarat',
        ],
        'python' => [
            'title' => 'Python Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab provides Python development in Rajkot, Gujarat, India—building scalable web apps, APIs, automation solutions, and data-driven systems.',
            'keywords' => 'affordable Python development services for startups in India Gujarat, best Python development company for web applications in India Gujarat, custom Python web application development services for business Gujarat, hire Python developers in India for backend development Gujarat, Python backend development services for scalable applications Gujarat, Python Django development services for web applications Gujarat, Python Flask development services for lightweight web apps Gujarat, Python API development and integration services Gujarat, Python development company for SaaS applications in India Gujarat, Python automation and scripting services for business processes Gujarat, outsource Python development services to India company Gujarat, Python development services with support and maintenance Gujarat, scalable Python development services for startups Gujarat, Python data processing and analytics application development services Gujarat, Python development company in Rajkot Gujarat India Gujarat',
        ],
        'codeigniter' => [
            'title' => 'CodeIgniter Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers CodeIgniter development in Rajkot, Gujarat, India—building fast, secure PHP apps, custom web solutions, APIs, and scalable systems.',
            'keywords' => 'CodeIgniter web portal development services for businesses in India Gujarat, lightweight PHP application development using CodeIgniter framework Gujarat, CodeIgniter custom module development services for enterprise apps Gujarat, CodeIgniter MVC architecture web development services India Gujarat, high performance CodeIgniter application development services Gujarat, CodeIgniter maintenance and bug fixing services for web apps Gujarat, CodeIgniter upgrade services from older PHP versions Gujarat, CodeIgniter website redesign and optimization services Gujarat, CodeIgniter backend system development for business applications Gujarat, secure CodeIgniter web development services for startups Gujarat, CodeIgniter CMS development services for dynamic websites Gujarat, CodeIgniter third party API integration services for web apps Gujarat, CodeIgniter database driven web application development services Gujarat, CodeIgniter performance tuning and speed optimization services Gujarat, CodeIgniter development services for custom business solutions in India Gujarat',
        ],
        'flutter' => [
            'title' => 'Flutter App Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab delivers Flutter app development in Rajkot, Gujarat, India—building fast, cross-platform Android & iOS apps with UI/UX, APIs, and support.',
            'keywords' => 'affordable Flutter mobile app development services for startups in India Gujarat, custom Flutter app development company for Android and iOS apps Gujarat, hire Flutter developers in India for cross platform app development Gujarat, Flutter mobile app development services for business applications Gujarat, best Flutter app development company for startups in India Gujarat, scalable Flutter app development services for enterprise solutions Gujarat, Flutter UI UX design and mobile app development services Gujarat, Flutter app development company for SaaS mobile applications Gujarat, cross platform mobile app development using Flutter framework Gujarat, Flutter ecommerce mobile app development services in India Gujarat, Flutter app integration services with REST API and backend Gujarat, Flutter app maintenance and support services for mobile apps Gujarat, Flutter mobile app development services with fast delivery in India Gujarat, Flutter app development company in Rajkot Gujarat India Gujarat, cost effective Flutter app development services for small businesses Gujarat',
        ],
        'react-native' => [
            'title' => 'React Native App Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab delivers React Native app development in Rajkot, Gujarat, India—building fast, cross-platform Android & iOS apps with modern UI and APIs.',
            'keywords' => 'affordable React Native app development services for startups in India Gujarat, custom React Native mobile app development company for Android and iOS Gujarat, hire React Native developers in India for cross platform apps Gujarat, React Native mobile app development services for business applications Gujarat, best React Native app development company for startups in India Gujarat, scalable React Native app development services for enterprise solutions Gujarat, React Native UI UX design and mobile app development services Gujarat, React Native app development company for SaaS mobile applications Gujarat, cross platform mobile app development using React Native framework Gujarat, React Native ecommerce mobile app development services in India Gujarat, React Native app integration services with REST API and backend Gujarat, React Native app maintenance and support services for mobile apps Gujarat, React Native mobile app development services with fast delivery in India Gujarat, React Native app development company in Rajkot Gujarat India Gujarat, cost effective React Native app development services for small businesses Gujarat',
        ],
        'android' => [
            'title' => 'Android App Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers Android app development in Rajkot, Gujarat, India—building fast, scalable apps with modern UI, API integration, and support.',
            'keywords' => 'affordable Android app development services for startups in India Gujarat, custom Android mobile app development company for business applications Gujarat, hire Android app developers in India for native app development Gujarat, Android application development services for scalable mobile solutions Gujarat, best Android app development company for startups in India Gujarat, Android ecommerce mobile app development services in India Gujarat, Android app development company for SaaS mobile applications Gujarat, Android app UI UX design and development services Gujarat, Android app integration services with REST API and backend systems Gujarat, Android app maintenance and support services for businesses Gujarat, enterprise Android application development services in India Gujarat, Android app development services with fast delivery and support Gujarat, Android mobile app development company in Rajkot Gujarat India Gujarat, cost effective Android app development services for small businesses Gujarat, Android app development services for on demand applications Gujarat',
        ],
        'ios' => [
            'title' => 'iOS App Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab delivers iOS app development in Rajkot, Gujarat, India—building secure, scalable apps with modern UI, API integration, and support.',
            'keywords' => 'affordable iOS app development services for startups in India Gujarat, custom iOS mobile app development company for business applications Gujarat, hire iOS app developers in India for native app development Gujarat, iOS application development services for scalable mobile solutions Gujarat, best iOS app development company for startups in India Gujarat, iOS ecommerce mobile app development services in India Gujarat, iOS app development company for SaaS mobile applications Gujarat, iOS app UI UX design and development services Gujarat, iOS app integration services with REST API and backend systems Gujarat, iOS app maintenance and support services for businesses Gujarat, enterprise iOS application development services in India Gujarat, iOS app development services with fast delivery and support Gujarat, iOS mobile app development company in Rajkot Gujarat India Gujarat, cost effective iOS app development services for small businesses Gujarat, iOS app development services for on demand applications Gujarat',
        ],
        'shopify' => [
            'title' => 'Shopify Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers Shopify development in Rajkot, Gujarat, India—building high-converting stores with custom themes, apps, integrations, and support.',
            'keywords' => 'affordable Shopify development services for small business in India Gujarat, custom Shopify store development company for ecommerce websites Gujarat, hire Shopify developers in India for online store setup Gujarat, Shopify ecommerce website development services for startups Gujarat, best Shopify development company for ecommerce business in India Gujarat, Shopify theme customization services for online stores Gujarat, Shopify store setup and configuration services in India Gujarat, Shopify app integration services for ecommerce websites Gujarat, Shopify migration services from WooCommerce to Shopify Gujarat, Shopify maintenance and support services for ecommerce stores Gujarat, Shopify speed optimization services for better performance Gujarat, Shopify SEO optimization services for ecommerce growth Gujarat, Shopify dropshipping store development services in India Gujarat, Shopify development company in Rajkot Gujarat India Gujarat, scalable Shopify ecommerce development services for businesses Gujarat',
        ],
        'magento' => [
            'title' => 'Magento Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers Magento development in Rajkot, Gujarat, India—building scalable ecommerce stores with custom modules, integrations, and support.',
            'keywords' => 'affordable Magento development services for ecommerce stores in India Gujarat, custom Magento ecommerce website development company for business Gujarat, hire Magento developers in India for online store development Gujarat, Magento ecommerce development services for scalable online businesses Gujarat, best Magento development company for enterprise ecommerce in India Gujarat, Magento store customization services for ecommerce websites Gujarat, Magento 2 development services for modern ecommerce platforms Gujarat, Magento migration services from Shopify or WooCommerce to Magento Gujarat, Magento API integration services for ecommerce applications Gujarat, Magento maintenance and support services for online stores Gujarat, Magento performance optimization services for ecommerce websites Gujarat, Magento B2B ecommerce development services for wholesalers Gujarat, Magento multi vendor marketplace development services in India Gujarat, Magento development company in Rajkot Gujarat India Gujarat, cost effective Magento ecommerce development services for startups Gujarat',
        ],
        'wordpress' => [
            'title' => 'WordPress Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers WordPress development in Rajkot, Gujarat, India—building fast, secure websites with custom themes, plugins, SEO, and support.',
            'keywords' => 'affordable WordPress development services for small business in India Gujarat, custom WordPress website development company for business websites Gujarat, hire WordPress developers in India for website development Gujarat, WordPress website development services for startups in India Gujarat, best WordPress development company for business websites in India Gujarat, WordPress theme customization services for websites Gujarat, WordPress plugin development services for custom features Gujarat, WordPress ecommerce development services using WooCommerce Gujarat, WordPress website redesign and optimization services Gujarat, WordPress speed optimization services for better performance Gujarat, WordPress SEO optimization services for website ranking Gujarat, WordPress maintenance and support services for websites Gujarat, WordPress migration services from other platforms to WordPress Gujarat, WordPress development company in Rajkot Gujarat India Gujarat, scalable WordPress website development services for businesses Gujarat',
        ],
        'aws' => [
            'title' => 'AWS Cloud Services Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers AWS cloud services in Rajkot, Gujarat, India—delivering scalable cloud solutions, migration, DevOps, and secure infrastructure management.',
            'keywords' => 'affordable AWS cloud consulting services for startups in India Gujarat, AWS cloud migration services for web applications and databases Gujarat, AWS infrastructure setup and configuration services for businesses Gujarat, AWS DevOps services for CI/CD pipeline automation in India Gujarat, AWS cloud architecture design services for scalable applications Gujarat, AWS managed services for cloud infrastructure maintenance and support Gujarat, AWS serverless application development services using Lambda Gujarat, AWS EC2 deployment and optimization services for web hosting Gujarat, AWS S3 storage setup and data management services for businesses Gujarat, AWS RDS database setup and migration services for applications Gujarat, AWS cloud security and compliance services for enterprise systems Gujarat, AWS cost optimization services for reducing cloud infrastructure expenses Gujarat, AWS monitoring and performance optimization services using CloudWatch Gujarat, AWS API Gateway and backend integration services for applications Gujarat, AWS Kubernetes (EKS) deployment and container management services Gujarat, AWS cloud backup and disaster recovery services for business continuity Gujarat, AWS SaaS application deployment and scaling services in India Gujarat, AWS cloud integration services with third party APIs and systems Gujarat, AWS cloud consulting and implementation services in Rajkot Gujarat India Gujarat, AWS cloud solutions provider for startups and small businesses Gujarat',
        ],
        'devops' => [
            'title' => 'DevOps Services Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers DevOps services in Rajkot, Gujarat, India—CI/CD, automation, cloud deployment, monitoring, and scalable infrastructure management.',
            'keywords' => 'DevOps services for small business cloud automation in Gujarat, affordable DevOps consulting services for startups in Gujarat, hire DevOps engineer India for CI CD pipeline setup Gujarat, DevOps automation services for web application deployment Gujarat, DevOps services for AWS cloud deployment and scaling Gujarat, DevOps services for Docker and Kubernetes deployment in Gujarat, DevOps pipeline setup services for startups Gujarat, DevOps cloud infrastructure management services for small business Gujarat, DevOps services for SaaS application deployment in Gujarat, DevOps monitoring and logging services for web applications Gujarat, DevOps infrastructure automation services using Terraform Gujarat, DevOps services for microservices deployment using Kubernetes Gujarat, DevOps continuous integration services for web applications Gujarat, DevOps services for backend deployment automation in Gujarat, DevOps cloud migration services for startups Gujarat, DevOps services for application performance optimization Gujarat, DevOps consulting services for startup infrastructure setup Gujarat, DevOps services for automated deployment and testing Gujarat, DevOps services for scalable cloud application deployment Gujarat, DevOps services in Rajkot Gujarat for small business Gujarat',
        ],
        'zoho' => [
            'title' => 'Zoho Services Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers Zoho services in Rajkot, Gujarat, India—CRM setup, customization, automation, integrations, and support for business growth.',
            'keywords' => 'Zoho CRM setup and customization services for small business in Gujarat, affordable Zoho CRM implementation services for startups Gujarat, Zoho CRM automation services for sales and lead management Gujarat, hire Zoho CRM developer in India for customization projects Gujarat, Zoho CRM integration services with website and mobile apps Gujarat, Zoho One implementation services for business automation in Gujarat, Zoho CRM data migration services from legacy systems Gujarat, Zoho Books setup and accounting automation services in Gujarat, Zoho Creator custom app development services for business Gujarat, Zoho inventory management system setup services for ecommerce Gujarat, Zoho CRM workflow automation services for small businesses Gujarat, Zoho CRM API integration services for web applications Gujarat, Zoho Desk setup and support services for customer service Gujarat, Zoho marketing automation services for lead generation Gujarat, Zoho CRM services in Rajkot Gujarat for small business Gujarat',
        ],
        'odoo' => [
            'title' => 'Odoo Development Company in Rajkot, Gujarat | Innoversion Technolab',
            'description' => 'Innoversion Technolab offers Odoo development in Rajkot, Gujarat, India—ERP implementation, customization, automation, integrations, and support.',
            'keywords' => 'affordable Odoo implementation services for small business in Gujarat, Odoo ERP development and customization services for startups Gujarat, hire Odoo developers in India for ERP customization projects Gujarat, Odoo ERP integration services with third party applications Gujarat, Odoo CRM setup and customization services for business automation Gujarat, Odoo accounting module setup services for small businesses in Gujarat, Odoo ecommerce website development services for online stores Gujarat, Odoo inventory management system implementation services Gujarat, Odoo ERP migration services from legacy systems to Odoo Gujarat, Odoo module development services for custom business requirements Gujarat, Odoo support and maintenance services for ERP systems Gujarat, Odoo ERP consulting services for business process optimization Gujarat, Odoo POS system setup services for retail businesses Gujarat, Odoo API integration services for web and mobile applications Gujarat, Odoo development company in Rajkot Gujarat India Gujarat',
        ],
    ],
];
